In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Public\Documents\Axel\libertadores26-data\matchStats\csv\fotmob_match_stats.csv')
df.tail()

,matchId,matchRound,homeTeamName,homeTeamid,awayTeamName,awayTeamid,home_goals,away_goals,ball_possession_home,ball_possession_away,...,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away,yellow_cards_home,yellow_cards_away,red_cards_home,red_cards_away
90,5261485,Group Stage - Round 6,Fluminense,9863,Deportivo La Guaira,176496,3,1,56,44,...,35 (48%),38 (52%),11 (73%),4 (27%),11 (65%),10 (63%),0,0,0,0
91,5261508,Group Stage - Round 6,Cerro Porteno,6295,Sporting Cristal,1848,2,0,51,49,...,37 (53%),33 (47%),16 (70%),7 (30%),6 (43%),5 (50%),0,0,0,0
92,5261509,Group Stage - Round 6,Palmeiras,10283,Junior FC,2254,4,1,49,51,...,55 (65%),30 (35%),6 (55%),5 (45%),15 (60%),8 (40%),0,0,0,0
93,5261542,Group Stage - Round 6,Boca Juniors,10077,Universidad Catolica,6458,0,1,71,29,...,46 (58%),34 (43%),23 (59%),16 (41%),13 (46%),2 (25%),0,0,0,0
94,5261543,Group Stage - Round 6,Cruzeiro,9781,Barcelona SC,6453,4,0,59,41,...,32 (53%),28 (47%),10 (53%),9 (47%),7 (58%),6 (100%),0,0,0,0

In [3]:
df.columns

Index(['matchId', 'matchRound', 'homeTeamName', 'homeTeamid', 'awayTeamName',
       'awayTeamid', 'home_goals', 'away_goals', 'ball_possession_home',
       'ball_possession_away', 'big_chances_home', 'big_chances_away',
       'big_chances_missed_home', 'big_chances_missed_away', 'fouls_home',
       'fouls_away', 'corners_home', 'corners_away', 'total_shots_home',
       'total_shots_away', 'shots_off_target_home', 'shots_off_target_away',
       'shots_on_target_home', 'shots_on_target_away', 'blocked_shots_home',
       'blocked_shots_away', 'hit_woodwork_home', 'hit_woodwork_away',
       'shots_inside_box_home', 'shots_inside_box_away',
       'shots_outside_box_home', 'shots_outside_box_away', 'xG_home',
       'xG_away', 'xG_open_play_home', 'xG_open_play_away', 'xG_set_play_home',
       'xG_set_play_away', 'xG_non_penalty_home', 'xG_non_penalty_away',
       'xGOT_home', 'xGOT_away', 'passes_home', 'passes_away',
       'accurate_passes_home', 'accurate_passes_away', 'own_half_passes_home',
       'own_half_passes_away', 'opposition_half_passes_home',
       'opposition_half_passes_away', 'accurate_long_passes_home',
       'accurate_long_passes_away', 'accurate_crosses_home',
       'accurate_crosses_away', 'throws_home', 'throws_away',
       'touches_opp_box_home', 'touches_opp_box_away', 'offsides_home',
       'offsides_away', 'tackles_won_home', 'tackles_won_away',
       'interceptions_home', 'interceptions_away', 'blocks_home',
       'blocks_away', 'clearances_home', 'clearances_away',
       'keeper_saves_home', 'keeper_saves_away', 'duel_won_home',
       'duel_won_away', 'ground_duels_won_home', 'ground_duels_won_away',
       'aerial_won_home', 'aerial_won_away', 'dribbles_succeeded_home',
       'dribbles_succeeded_away', 'yellow_cards_home', 'yellow_cards_away',
       'red_cards_home', 'red_cards_away'],
      dtype='str')

In [3]:
# Get the row with the highest ball possession playing home
df.loc[[df['ball_possession_home'].idxmax()], ['matchRound', 'homeTeamName', 'awayTeamName', 'home_goals', 'away_goals', 'ball_possession_home', 'ball_possession_away']]

,matchRound,homeTeamName,awayTeamName,home_goals,away_goals,ball_possession_home,ball_possession_away
46,3,Corinthians,Club Atletico Penarol,2,0,78,22

In [29]:
# Get the row with the lowest ball possession playing home
df.loc[[df['ball_possession_home'].idxmin()], ['matchRound', 'homeTeamName', 'awayTeamName', 'home_goals', 'away_goals', 'ball_possession_home', 'ball_possession_away']]

,matchRound,homeTeamName,awayTeamName,home_goals,away_goals,ball_possession_home,ball_possession_away
55,4,Independiente Rivadavia,Fluminense,1,1,27,73

In [31]:
# Get the row with the highest ball possession playing away
df.loc[[df['ball_possession_away'].idxmax()], ['matchRound', 'homeTeamName', 'awayTeamName', 'home_goals', 'away_goals', 'ball_possession_home', 'ball_possession_away']]

,matchRound,homeTeamName,awayTeamName,home_goals,away_goals,ball_possession_home,ball_possession_away
55,4,Independiente Rivadavia,Fluminense,1,1,27,73

In [32]:
# Get the row with the lowest ball possession playing away
df.loc[[df['ball_possession_away'].idxmin()], ['matchRound', 'homeTeamName', 'awayTeamName', 'home_goals', 'away_goals', 'ball_possession_home', 'ball_possession_away']]

,matchRound,homeTeamName,awayTeamName,home_goals,away_goals,ball_possession_home,ball_possession_away
46,3,Corinthians,Club Atletico Penarol,2,0,78,22

In [4]:
# Get the top 10 with the most ball possession playing HOME
df.nlargest(10, 'ball_possession_home')[['matchRound', 'homeTeamName', 'awayTeamName', 'home_goals', 'away_goals', 'ball_possession_home', 'ball_possession_away']]

,matchRound,homeTeamName,awayTeamName,home_goals,away_goals,ball_possession_home,ball_possession_away
46,3,Corinthians,Club Atletico Penarol,2,0,78,22
89,Group Stage - Round 6,Corinthians,Club Atletico Platense,0,2,77,23
78,5,Universidad Catolica,Barcelona SC,2,0,76,24
64,5,Fluminense,Bolivar,2,1,74,26
73,5,Palmeiras,Cerro Porteno,0,1,74,26
20,2,Bolivar,Deportivo La Guaira,1,1,72,28
81,6,Estudiantes,Independiente Medellin,1,0,72,28
26,2,Fluminense,Independiente Rivadavia,1,2,71,29
93,Group Stage - Round 6,Boca Juniors,Universidad Catolica,0,1,71,29
6,1,Coquimbo Unido,Nacional,1,1,68,32

In [5]:
# Get the top 10 with the lowest ball possession playing HOME using nsmallest()
df.nsmallest(10, 'ball_possession_home')[['matchRound', 'homeTeamName', 'awayTeamName', 'home_goals', 'away_goals', 'ball_possession_home', 'ball_possession_away']]

,matchRound,homeTeamName,awayTeamName,home_goals,away_goals,ball_possession_home,ball_possession_away
55,4,Independiente Rivadavia,Fluminense,1,1,27,73
51,4,Universidad Central,Independiente del Valle,2,0,32,68
24,2,Libertad,Rosario Central,0,1,33,67
63,5,Coquimbo Unido,Tolima,3,0,33,67
83,6,Nacional,Coquimbo Unido,1,0,33,67
41,3,Cerro Porteno,Palmeiras,1,1,34,66
77,5,Club Atletico Penarol,Corinthians,1,1,35,65
0,1,Deportivo La Guaira,Fluminense,0,0,36,64
1,1,Independiente Rivadavia,Bolivar,1,0,36,64
21,2,LDU de Quito,Mirassol,2,0,39,61